import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#e2bfb0",
        outline: "#a98a7d",
        "surface-variant": "#353534",
        "surface-container": "#201f1f",
        "on-primary": "#561f00",
        "primary-fixed": "#ffdbcc",
        "on-secondary-fixed": "#410000",
        "surface-dim": "#131313",
        "surface-tint": "#ffb693",
        "on-primary-fixed-variant": "#7a3000",
        "primary-fixed-dim": "#ffb693",
        error: "#ffb4ab",
        "on-tertiary-container": "#313131",
        background: "#131313",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#474746",
        "tertiary-fixed-dim": "#c8c6c5",
        surface: "#131313",
        "inverse-primary": "#a04100",
        "tertiary-container": "#9a9898",
        "on-tertiary": "#313030",
        "on-secondary-fixed-variant": "#930100",
        "error-container": "#93000a",
        "secondary-fixed": "#ffdad4",
        "primary-container": "#ff6b00",
        "inverse-surface": "#e5e2e1",
        "on-error": "#690005",
        "on-secondary-container": "#fff6f5",
        "on-secondary": "#690000",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#1c1b1b",
        "outline-variant": "#5a4136",
        tertiary: "#c8c6c5",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed": "#351000",
        "secondary-container": "#e60000",
        "on-primary-container": "#572000",
        primary: "#ffb693",
        "tertiary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        secondary: "#ffb4a8",
        "surface-bright": "#3a3939",
        "secondary-fixed-dim": "#ffb4a8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "container-margin": "24px",
        "section-gap": "40px",
        unit: "8px",
      },
      fontFamily: {
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "mono-data": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "mono-data": ["14px", { lineHeight: "1.0", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      backgroundImage: {
        "grid-pattern":
          "linear-gradient(to right, rgba(255, 255, 255, 0.03) 1px, transparent 1px), linear-gradient(to bottom, rgba(255, 255, 255, 0.03) 1px, transparent 1px)",
      },
      backgroundSize: {
        grid: "24px 24px",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
      },
      animation: {
        shimmer: "shimmer 1.6s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
